[package]
name = "DustyControl"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13", features = ["tokio", "canvas"] }
sysinfo = "0.33"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
rodio = "0.19"
chrono = "0.4"

libc = "0.2"

[target.'cfg(any(target_os = "linux", target_os = "windows"))'.dependencies]
nvml-wrapper = "0.10"
